apiVersion: scheduler.kalypso.io/v1alpha1
kind: Template
metadata:
  labels:
    someLabel: "false"
  name: arc-flux
spec:
  type: reconciler
  manifests:
    - |
      apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      metadata:
        name: {{ .Environment}}.{{ .Workspace}}.{{ index .Labels "use-case"}}.{{ .DeploymentTargetName}}.{{ .ClusterType}}
        namespace: flux-system
      spec:
        interval: 30s
        url: {{ .Manifests.repo}}
        ref:
          branch: {{ .Manifests.branch}}
        secretRef:
            name: repo-secret    
    - |
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: {{ .Environment}}.{{ .Workspace}}.{{ index .Labels "use-case"}}.{{ .DeploymentTargetName}}.{{ .ClusterType}}
        namespace: flux-system
      spec:
        interval: 30s
        targetNamespace: {{ .Namespace}}
        sourceRef:
          kind: GitRepository
          name: {{ .Environment}}.{{ .Workspace}}.{{ index .Labels "use-case"}}.{{ .DeploymentTargetName}}.{{ .ClusterType}}
        path: {{ .Manifests.path}} 
        suspend: false
        prune: true
